Added React Roter, Page folder
paulavanina/invingem-impreuna-app pull request #2
Opened 2024-07-25 07:32 UTC by paulavanina

2024-07-25 07:42 UTC, milosanca requested changes

2024-07-25 07:42 UTC, milosanca commented on src/components/Features/FeaturesImages.tsx
> +    <div className={classes.item} key={item.image}>
add an ID to the data array and ise the ID as key instead of the image

2024-07-25 08:45 UTC, silviuvld requested changes

2024-07-25 08:45 UTC, silviuvld commented on src/components/HeroHeader/HeroHeader.module.css
> +  /* padding-top: calc(var(--mantine-spacing-xl) * 4); */
why we have comments in code?

2024-07-25 08:45 UTC, silviuvld commented on src/App.tsx
> +// import { HeaderMegaMenu } from "./components/Header/HeadeMegaMenu"
why we have comments in code?

2024-07-25 08:45 UTC, silviuvld commented on src/App.tsx
> +    {/* <HeaderMegaMenu />
why we have comments in code?

2024-07-26 07:09 UTC, milosanca approved these changes

2024-07-26 07:09 UTC, merged